# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.5
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.api.networks_api import NetworksApi  # noqa: E501
from pysbml4j.rest import ApiException


class TestNetworksApi(unittest.TestCase):
    """NetworksApi unit test stubs"""

    def setUp(self):
        self.api = NetworksApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_annotation_to_network(self):
        """Test case for add_annotation_to_network

        Add annotation to network nodes and/or relationships. Results in the creation of a new network entity, keeping the entity with UUID unchanged.   # noqa: E501
        """
        pass

    def test_add_my_drug_relations(self):
        """Test case for add_my_drug_relations

        Provide a URL to a MyDrug Neo4j Database and add Drug nodes and Drug-targets->Gene Relationships to a network  # noqa: E501
        """
        pass

    def test_copy_network(self):
        """Test case for copy_network

        Create a copy of the network with uuid UUID  # noqa: E501
        """
        pass

    def test_delete_network(self):
        """Test case for delete_network

        Request the deletion of a network  # noqa: E501
        """
        pass

    def test_filter_network(self):
        """Test case for filter_network

        Filter a network according to the request body options. Results in the creation of a new network entity, keeping the entity with UUID unchanged.  # noqa: E501
        """
        pass

    def test_get_context(self):
        """Test case for get_context

        Get network context of one or multiple genes in the network with uuid {UUID}  # noqa: E501
        """
        pass

    def test_get_network(self):
        """Test case for get_network

        Retrieve the contents of a network  # noqa: E501
        """
        pass

    def test_get_network_options(self):
        """Test case for get_network_options

        Get available options for network  # noqa: E501
        """
        pass

    def test_list_all_networks(self):
        """Test case for list_all_networks

        List available networks  # noqa: E501
        """
        pass

    def test_post_context(self):
        """Test case for post_context

        Create network context of one or multiple genes in the network with uuid {UUID}  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
