# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.5
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.models.reaction_partner_item import ReactionPartnerItem  # noqa: E501
from pysbml4j.rest import ApiException


class TestReactionPartnerItem(unittest.TestCase):
    """ReactionPartnerItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testReactionPartnerItem(self):
        """Test ReactionPartnerItem"""
        # FIXME: construct object with mandatory attributes with example values
        # model = pysbml4j.models.reaction_partner_item.ReactionPartnerItem()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
