# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.5
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.api.sbml_api import SbmlApi  # noqa: E501
from pysbml4j.rest import ApiException


class TestSbmlApi(unittest.TestCase):
    """SbmlApi unit test stubs"""

    def setUp(self):
        self.api = SbmlApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_upload_sbml(self):
        """Test case for upload_sbml

        Upload SBML Model to create a Pathway  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
