# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.5
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.api.analysis_api import AnalysisApi  # noqa: E501
from pysbml4j.rest import ApiException


class TestAnalysisApi(unittest.TestCase):
    """AnalysisApi unit test stubs"""

    def setUp(self):
        self.api = AnalysisApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_gene_analysis(self):
        """Test case for get_gene_analysis

        Relation- and Pathway Analysis for a gene  # noqa: E501
        """
        pass

    def test_get_gene_set(self):
        """Test case for get_gene_set

        provide a list of genes and get a network containing all genes and their respective relations  # noqa: E501
        """
        pass

    def test_get_gene_set_analysis(self):
        """Test case for get_gene_set_analysis

        Relation- and Pathway Analysis for a set of genes  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
