# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.5
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.api.pathways_api import PathwaysApi  # noqa: E501
from pysbml4j.rest import ApiException


class TestPathwaysApi(unittest.TestCase):
    """PathwaysApi unit test stubs"""

    def setUp(self):
        self.api = PathwaysApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_pathway_collection(self):
        """Test case for create_pathway_collection

        Create a collectionPathway from the submitted pathways  # noqa: E501
        """
        pass

    def test_list_all_pathway_uui_ds(self):
        """Test case for list_all_pathway_uui_ds

        List UUIDs of available pathways  # noqa: E501
        """
        pass

    def test_list_all_pathways(self):
        """Test case for list_all_pathways

        List available pathways  # noqa: E501
        """
        pass

    def test_map_pathway(self):
        """Test case for map_pathway

        Map pathwayContents on a new network representation  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
