# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.4
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.api.mydrug_api import MydrugApi  # noqa: E501
from pysbml4j.rest import ApiException


class TestMydrugApi(unittest.TestCase):
    """MydrugApi unit test stubs"""

    def setUp(self):
        self.api = MydrugApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_my_drug_relations(self):
        """Test case for add_my_drug_relations

        Provide a URL to a MyDrug Neo4j Database and add Drug nodes and Drug-targets->Gene Relationships to a network  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
