# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.5
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.api.convenience_api import ConvenienceApi  # noqa: E501
from pysbml4j.rest import ApiException


class TestConvenienceApi(unittest.TestCase):
    """ConvenienceApi unit test stubs"""

    def setUp(self):
        self.api = ConvenienceApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_overview_network(self):
        """Test case for create_overview_network

        upload a set of genes and get a network connecting them  # noqa: E501
        """
        pass

    def test_get_overview_network(self):
        """Test case for get_overview_network

        retrieve a previously created overview network for a user by its name  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
