# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.4
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import pysbml4j
from pysbml4j.api.documentation_api import DocumentationApi  # noqa: E501
from pysbml4j.rest import ApiException


class TestDocumentationApi(unittest.TestCase):
    """DocumentationApi unit test stubs"""

    def setUp(self):
        self.api = DocumentationApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_base_documentation(self):
        """Test case for get_base_documentation

        Show the API help  # noqa: E501
        """
        pass

    def test_get_db_status(self):
        """Test case for get_db_status

        Get the status of the connected database  # noqa: E501
        """
        pass

    def test_get_profile(self):
        """Test case for get_profile

        Get the active profile of sbml4j running  # noqa: E501
        """
        pass

    def test_get_version(self):
        """Test case for get_version

        Get the version of sbml4j running  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
