# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.4
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from pysbml4j.api_client import ApiClient


class AnalysisApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def get_gene_analysis(self, gene_symbol, **kwargs):  # noqa: E501
        """Relation- and Pathway Analysis for a gene  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_gene_analysis(gene_symbol, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str gene_symbol: The geneSymbol for which the analysis should be fetched (required)
        :return: list[GeneAnalysisItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_gene_analysis_with_http_info(gene_symbol, **kwargs)  # noqa: E501
        else:
            (data) = self.get_gene_analysis_with_http_info(gene_symbol, **kwargs)  # noqa: E501
            return data

    def get_gene_analysis_with_http_info(self, gene_symbol, **kwargs):  # noqa: E501
        """Relation- and Pathway Analysis for a gene  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_gene_analysis_with_http_info(gene_symbol, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str gene_symbol: The geneSymbol for which the analysis should be fetched (required)
        :return: list[GeneAnalysisItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['gene_symbol']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_gene_analysis" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'gene_symbol' is set
        if ('gene_symbol' not in params or
                params['gene_symbol'] is None):
            raise ValueError("Missing the required parameter `gene_symbol` when calling `get_gene_analysis`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'gene_symbol' in params:
            query_params.append(('geneSymbol', params['gene_symbol']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/geneAnalysis', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[GeneAnalysisItem]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_gene_set(self, user, gene_symbols, **kwargs):  # noqa: E501
        """provide a list of genes and get a network containing all genes and their respective relations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_gene_set(user, gene_symbols, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str user: The user which requests the creation (required)
        :param list[str] gene_symbols: The geneSymbols for which the analysis should be fetched (required)
        :param str uuid: The UUID of the parent network to derive a new network from, if omitted the full model will be used
        :param bool directed: Boolean flag wether the resulting network-graph should be directed 
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_gene_set_with_http_info(user, gene_symbols, **kwargs)  # noqa: E501
        else:
            (data) = self.get_gene_set_with_http_info(user, gene_symbols, **kwargs)  # noqa: E501
            return data

    def get_gene_set_with_http_info(self, user, gene_symbols, **kwargs):  # noqa: E501
        """provide a list of genes and get a network containing all genes and their respective relations  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_gene_set_with_http_info(user, gene_symbols, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str user: The user which requests the creation (required)
        :param list[str] gene_symbols: The geneSymbols for which the analysis should be fetched (required)
        :param str uuid: The UUID of the parent network to derive a new network from, if omitted the full model will be used
        :param bool directed: Boolean flag wether the resulting network-graph should be directed 
        :return: str
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['user', 'gene_symbols', 'uuid', 'directed']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_gene_set" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'user' is set
        if ('user' not in params or
                params['user'] is None):
            raise ValueError("Missing the required parameter `user` when calling `get_gene_set`")  # noqa: E501
        # verify the required parameter 'gene_symbols' is set
        if ('gene_symbols' not in params or
                params['gene_symbols'] is None):
            raise ValueError("Missing the required parameter `gene_symbols` when calling `get_gene_set`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'uuid' in params:
            query_params.append(('UUID', params['uuid']))  # noqa: E501
        if 'gene_symbols' in params:
            query_params.append(('geneSymbols', params['gene_symbols']))  # noqa: E501
            collection_formats['geneSymbols'] = 'csv'  # noqa: E501
        if 'directed' in params:
            query_params.append(('directed', params['directed']))  # noqa: E501

        header_params = {}
        if 'user' in params:
            header_params['user'] = params['user']  # noqa: E501

        form_params = []
        local_var_files = {}

        body_params = None
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/octet-stream'])  # noqa: E501

        # Authentication setting
        auth_settings = ['network_auth']  # noqa: E501

        return self.api_client.call_api(
            '/geneSet', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='str',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def get_gene_set_analysis(self, body, **kwargs):  # noqa: E501
        """Relation- and Pathway Analysis for a set of genes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_gene_set_analysis(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: A json formatted and comma separated list of genes in the set to be analysed
 (required)
        :return: list[GeneAnalysisItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.get_gene_set_analysis_with_http_info(body, **kwargs)  # noqa: E501
        else:
            (data) = self.get_gene_set_analysis_with_http_info(body, **kwargs)  # noqa: E501
            return data

    def get_gene_set_analysis_with_http_info(self, body, **kwargs):  # noqa: E501
        """Relation- and Pathway Analysis for a set of genes  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.get_gene_set_analysis_with_http_info(body, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param list[str] body: A json formatted and comma separated list of genes in the set to be analysed
 (required)
        :return: list[GeneAnalysisItem]
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method get_gene_set_analysis" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'body' is set
        if ('body' not in params or
                params['body'] is None):
            raise ValueError("Missing the required parameter `body` when calling `get_gene_set_analysis`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/geneSetAnalysis', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='list[GeneAnalysisItem]',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
