# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.4
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class PathwayInfoItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'kegg_id': 'str',
        'kegg_url': 'str'
    }

    attribute_map = {
        'name': 'name',
        'kegg_id': 'KEGGId',
        'kegg_url': 'KEGGUrl'
    }

    def __init__(self, name=None, kegg_id=None, kegg_url=None):  # noqa: E501
        """PathwayInfoItem - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._kegg_id = None
        self._kegg_url = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if kegg_id is not None:
            self.kegg_id = kegg_id
        if kegg_url is not None:
            self.kegg_url = kegg_url

    @property
    def name(self):
        """Gets the name of this PathwayInfoItem.  # noqa: E501

        The name of the Pathway  # noqa: E501

        :return: The name of this PathwayInfoItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PathwayInfoItem.

        The name of the Pathway  # noqa: E501

        :param name: The name of this PathwayInfoItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def kegg_id(self):
        """Gets the kegg_id of this PathwayInfoItem.  # noqa: E501

        The Kegg pathways identifier  # noqa: E501

        :return: The kegg_id of this PathwayInfoItem.  # noqa: E501
        :rtype: str
        """
        return self._kegg_id

    @kegg_id.setter
    def kegg_id(self, kegg_id):
        """Sets the kegg_id of this PathwayInfoItem.

        The Kegg pathways identifier  # noqa: E501

        :param kegg_id: The kegg_id of this PathwayInfoItem.  # noqa: E501
        :type: str
        """

        self._kegg_id = kegg_id

    @property
    def kegg_url(self):
        """Gets the kegg_url of this PathwayInfoItem.  # noqa: E501

        The Url to retrieve the map from KEGG  # noqa: E501

        :return: The kegg_url of this PathwayInfoItem.  # noqa: E501
        :rtype: str
        """
        return self._kegg_url

    @kegg_url.setter
    def kegg_url(self, kegg_url):
        """Sets the kegg_url of this PathwayInfoItem.

        The Url to retrieve the map from KEGG  # noqa: E501

        :param kegg_url: The kegg_url of this PathwayInfoItem.  # noqa: E501
        :type: str
        """

        self._kegg_url = kegg_url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PathwayInfoItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PathwayInfoItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
