# coding: utf-8

"""
    sbml4j API

    This is the api for the SBML4j Service   # noqa: E501

    OpenAPI spec version: 1.1.4
    Contact: thorsten.tiede@uni-tuebingen.de
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WarehouseInventoryItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'str',
        'name': 'str',
        'organism_code': 'str'
    }

    attribute_map = {
        'uuid': 'UUID',
        'name': 'name',
        'organism_code': 'organismCode'
    }

    def __init__(self, uuid=None, name=None, organism_code=None):  # noqa: E501
        """WarehouseInventoryItem - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._name = None
        self._organism_code = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if name is not None:
            self.name = name
        if organism_code is not None:
            self.organism_code = organism_code

    @property
    def uuid(self):
        """Gets the uuid of this WarehouseInventoryItem.  # noqa: E501


        :return: The uuid of this WarehouseInventoryItem.  # noqa: E501
        :rtype: str
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this WarehouseInventoryItem.


        :param uuid: The uuid of this WarehouseInventoryItem.  # noqa: E501
        :type: str
        """

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this WarehouseInventoryItem.  # noqa: E501


        :return: The name of this WarehouseInventoryItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WarehouseInventoryItem.


        :param name: The name of this WarehouseInventoryItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def organism_code(self):
        """Gets the organism_code of this WarehouseInventoryItem.  # noqa: E501

        Three letter organism code this network belongs to  # noqa: E501

        :return: The organism_code of this WarehouseInventoryItem.  # noqa: E501
        :rtype: str
        """
        return self._organism_code

    @organism_code.setter
    def organism_code(self, organism_code):
        """Sets the organism_code of this WarehouseInventoryItem.

        Three letter organism code this network belongs to  # noqa: E501

        :param organism_code: The organism_code of this WarehouseInventoryItem.  # noqa: E501
        :type: str
        """

        self._organism_code = organism_code

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WarehouseInventoryItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WarehouseInventoryItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
